# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: deploy to EC2

on:
  push:
    branches: 
       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses : actions/checkout@v4.2.2
        with:
            ip : ${{ secrets.EC2_INSTANCE_IP }}
            key : ${{ secrets.EC2_KEY }}
            port : ${{ secrets.EC2_PORT }}
            script:
              cd/desktop/aws/key-pair
              ssh -i gnusead-ec2-key.pem ubuntu@${{ secrets.EC2_KEY }}
              cd/my-selectshop
              git pull origin main
              pm2 kill
              yarn add --force
              PORT=${{ secrets.EC2_PORT }} pm2 --name my-selectshop statt yarn -- dev
              
